server:
  port: 9090
  servlet:
    context-path: /demo

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://172.16.5.127:3306/mydemo?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC&：&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*Mapping.xml
  type-aliases-package: com.example.mapper
